fail_fast: True

repos:

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.3.1
  hooks:
  - id: add-license-headers

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 24.4.2  # If version changes --> modify "blacken-docs" manually as well.
  hooks:
  - id: black
    args:
      - --line-length=88

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==24.4.2]


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.3
  hooks:
    - id: check-github-workflows
